# Owner/Author information

url: "https://guomin.darlings.life"

author:
  name:             和敏宝打怪升级
  avatar:           /assets/img/avatar.png
  email:            wuzhimang@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  github:           https://github.com/codeshold
  linkedin:         https://cn.linkedin.com/in/wenfeng-shi-643474129
  douban:           https://www.douban.com/people/138288726/
  xhs:              https://www.xiaohongshu.com/user/profile/5e3398d700000000010041d7
  twitter:          https://twitter.com/wuzhimang
  wechat:           /assets/img/wechat.png
  qq:               /assets/img/qq.png
  resume:           /nothings/empty.pdf


# 站点信息
title:             和敏宝打怪升级
description:       过敏知识分享, Allergies're simple!
production_url:    https://guomin.darlings.life    # production_url是sitemap生成的url,方便百度谷歌收录.


# url_tags必须和tags.md中的permalink定义相同，这样定义的原因是不希望permalink中包含文件类型后缀。
# 或者tags.md中不定义permalink，这里直接引用tags.md的在目录中的绝对地址。
# 其它几个url也需要遵循这个原则。
# 
url_rss:            /pages/atom.xml
url_about:          /pages/about.html
url_archives:       /pages/archive.html
url_atom:           /pages/atom.html
url_tags:           /pages/tags.html

# gavatar头像及Favicon
favicon:            /assets/img/favicon.ico
gavatar:            /assets/img/avatar.png



# google analytics 设置
ga:
  id: G-DL095PZG0V
  url: guomin.darlings.life

# disqus 设置
# Set Up Disqus On a Your Own Site, this shortname is your unique Disqus URL.
# something like this: shortname.disqus.com


# 主题设置，自动激活某个分类
active: 过敏


# 首页除了最新文章外显示分类
cates: 
  - 过敏
  - 读书
  - 翻译


# 中文本地化
locals:
  tags: "# 标签"
  about: "# 关于"
  newest: "最新文章"
  archive: "# 归档"

  
# Background image to be tiled on all pages
background: 


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:title.html
relative_permalinks: false


# Amount of newest post to show on home page
paginate: 8
paginate_path: "/page:num"


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
          
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter: rouge

include: []

exclude: ["README.md", "vendor", ".bundle", "node_modules", "Gemfile.lock", "Gemfile"]

plugins: []
#plugins:
#- jekyll-paginate
#- jekyll-sitemap
##- jekyll-github-metadata
#- jekyll-mentions
#- jekyll-redirect-from
##- jemojirepository: username/repo-name
